baseURL = "https://krustlet-docs.netlify.app/"
languageCode = "en-us"
title = "Documentation for Krustlet"
theme = "krustlet"

# Theme General Config
[languages]
[languages.en]
title = "Krustlet"
description = "Documentation for Krustlet"
languageName ="English"
weight = 1
navbar_logo = false

[services]
[services.googleAnalytics]
id = "UA-130516746-11"
enableRobotsTXT = true
enableGitInfo = true
contentDir = "content"
version_menu = "Releases"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableMissingTranslationPlaceholders = true
disableKinds = ["taxonomy", "taxonomyTerm"]
pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsUseClassic = false
pygmentsStyle = "tango"
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "tomorrow-night"


# OSM top menu (should match main site)
[[menu.main]]
	name = "Home"
	weight = 10
	url = "https://krustlet.dev"
[[menu.main]]
	name = "Docs"
	weight = 20
	url = "https://docs.deislabs.io/krustlet"
[[menu.main]]
	name = "Github"
	weight = 30
	url = "https://github.com/deislabs/krustlet/"
[[menu.main]]
	name = "Slack"
	weight = 50
	url = "https://kubernetes.slack.com/messages/krustlet"
[[menu.main]]
	name = "Twitter"
	weight = 60
	url = "https://twitter.com/krustlet"


# Add your release versions here
[[params.versions]]
  version = "v0.7.0"
  url = "https://docs.deislabs.io/krustlet"


# Theme Additional params
[params]
copyright = "The Docsy Authors"
offlineSearch = true
prism_syntax_highlighting = true

[params.ui]
navbar_logo = true
navbar_logo_img = "logos/full.png"
sidebar_menu_compact = false
breadcrumb_disable = false
sidebar_search_disable = false
parent = "Deis Labs"
parent_url = "https://krustlet.dev"
footer_logo = true
footer_logo_img = "logos/deislabs.png"
footer_url = "ttps://docs.deislabs.io/krustlet"
ul_show = 0

[params.ui.feedback]
enable = false
